
import React, { useState, useMemo } from 'react';
import { Device, DeviceStatus, DiagnosticReport, DeviceCategory, MetricConfig } from '../types';
import { getDeviceDiagnostic } from '../geminiService';
import { jsPDF } from "jspdf";
import { resolveMetricMetadata } from '../constants'; // Use the new helper

interface MonitorPageProps {
  devices: Device[];
  categories: DeviceCategory[];
  metricConfig: MetricConfig; // Receive dynamic config
}

const getStatusColor = (status: DeviceStatus) => {
  switch (status) {
    case DeviceStatus.ONLINE: return 'bg-emerald-500';
    case DeviceStatus.WARNING: return 'bg-amber-500';
    case DeviceStatus.CRITICAL: return 'bg-rose-500';
    default: return 'bg-slate-400';
  }
};

const MiniSparkline = ({ data, color }: { data: number[], color: string }) => {
  // If no data, render placeholder
  if (!data || data.length === 0) return <div className="w-full h-8 bg-slate-50 rounded"></div>;
  
  const max = Math.max(...data) * 1.1 || 100; // Add 10% buffer or default to 100
  const min = 0;
  const range = max - min;
  
  const points = data.map((v, i) => {
      const x = (i / (data.length - 1)) * 100;
      const y = 100 - ((v - min) / range) * 100;
      return `${x},${y}`;
  }).join(' ');

  return (
    <svg className="w-full h-8 overflow-visible" viewBox="0 0 100 100" preserveAspectRatio="none">
      <polyline 
        fill="none" 
        stroke={color} 
        strokeWidth="4" 
        strokeLinecap="round" 
        strokeLinejoin="round" 
        points={points} 
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  );
};

export const MonitorPage: React.FC<MonitorPageProps> = ({ devices, categories, metricConfig }) => {
  const [selectedDeviceId, setSelectedDeviceId] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [diagnosticReport, setDiagnosticReport] = useState<DiagnosticReport | null>(null);
  
  // Filter States
  const [statusFilter, setStatusFilter] = useState<DeviceStatus | 'ALL'>('ALL');
  const [categoryFilter, setCategoryFilter] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  // Only find the device if selectedDeviceId is set (Modal Logic)
  const selectedDevice = useMemo(() => 
    selectedDeviceId ? devices.find(d => d.id === selectedDeviceId) : null, 
  [devices, selectedDeviceId]);

  const filteredDevices = useMemo(() => {
      return devices.filter(d => {
          const matchStatus = statusFilter === 'ALL' || d.status === statusFilter;
          const matchCategory = categoryFilter === 'ALL' || d.categoryId === categoryFilter;
          const matchSearch = !searchQuery || 
              d.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
              d.ip.includes(searchQuery) ||
              d.id.toLowerCase().includes(searchQuery.toLowerCase());
          
          return matchStatus && matchCategory && matchSearch;
      });
  }, [devices, statusFilter, categoryFilter, searchQuery]);

  const handleAnalyze = async () => {
    if (!selectedDevice) return;
    setIsAnalyzing(true);
    setDiagnosticReport(null);
    const report = await getDeviceDiagnostic(selectedDevice);
    setDiagnosticReport(report);
    setIsAnalyzing(false);
  };

  const handleExportPDF = () => {
      if (!selectedDevice || !diagnosticReport) return;

      const doc = new jsPDF();
      // ... (Same PDF logic as before) ...
      doc.setFontSize(20);
      doc.text("AI Diagnostic Report", 20, 20);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated by AuraSense AI • ${new Date().toLocaleString()}`, 20, 26);
      doc.setDrawColor(200);
      doc.line(20, 30, 190, 30);
      doc.setTextColor(0);
      doc.setFontSize(12);
      doc.text(`Device Name: ${selectedDevice.name}`, 20, 40);
      doc.text(`Device ID: ${selectedDevice.id}`, 20, 46);
      doc.text(`Type: ${selectedDevice.type}`, 120, 40);
      doc.text(`Location: ${selectedDevice.location}`, 120, 46);
      doc.setFontSize(14);
      doc.text("Health Assessment", 20, 60);
      doc.setFontSize(12);
      if (diagnosticReport.status === 'Healthy') doc.setTextColor(0, 150, 0);
      else if (diagnosticReport.status === 'Risk') doc.setTextColor(200, 100, 0);
      else doc.setTextColor(200, 0, 0);
      doc.text(`Status: ${diagnosticReport.status.toUpperCase()}`, 20, 68);
      doc.setTextColor(0);
      doc.setFontSize(14);
      doc.text("Executive Summary", 20, 85);
      doc.setFontSize(10);
      doc.setTextColor(60);
      const summaryLines = doc.splitTextToSize(diagnosticReport.summary, 170);
      doc.text(summaryLines, 20, 93);
      let currentY = 93 + summaryLines.length * 5 + 10;
      doc.setTextColor(0);
      doc.setFontSize(14);
      doc.text("Detected Anomalies", 20, currentY);
      currentY += 8;
      doc.setFontSize(10);
      doc.setTextColor(60);
      if (diagnosticReport.anomaliesFound.length > 0) {
          diagnosticReport.anomaliesFound.forEach(anomaly => {
              doc.text(`• ${anomaly}`, 20, currentY);
              currentY += 6;
          });
      } else {
          doc.text("• No anomalies detected.", 20, currentY);
          currentY += 6;
      }
      currentY += 10;
      doc.setTextColor(0);
      doc.setFontSize(14);
      doc.text("Actionable Recommendations", 20, currentY);
      currentY += 8;
      doc.setFontSize(10);
      doc.setTextColor(60);
      diagnosticReport.recommendations.forEach(rec => {
          doc.text(`• ${rec}`, 20, currentY);
          currentY += 6;
      });
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Confidential - Internal Use Only", 105, 280, { align: "center" });
      doc.save(`AuraSense_Report_${selectedDevice.id}_${Date.now()}.pdf`);
  };

  const handleCloseModal = () => {
      setSelectedDeviceId(null);
      setDiagnosticReport(null);
      setIsAnalyzing(false);
  };

  return (
    <div className="flex flex-col h-full space-y-6">
      {/* Filter Bar (Same as before) */}
      <div className="flex flex-col xl:flex-row justify-between xl:items-center bg-white p-4 rounded-3xl border border-slate-100 shadow-sm gap-4 flex-shrink-0">
          <div className="flex flex-col md:flex-row md:items-center gap-4 flex-1">
              <div>
                  <h3 className="text-lg font-black text-slate-800">全域设备监控</h3>
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Global Device Monitoring</p>
              </div>
              <div className="hidden md:block w-px h-8 bg-slate-100"></div>
              <div className="relative flex-1 max-w-sm">
                  <input type="text" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="搜索设备名称 / IP / ID..." className="w-full pl-9 pr-4 py-2.5 bg-slate-50 border border-slate-100 rounded-xl text-xs font-bold text-slate-700 outline-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-300 transition-all placeholder-slate-400" />
                  <svg className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
              </div>
              <div className="relative w-48">
                  <select value={categoryFilter} onChange={(e) => setCategoryFilter(e.target.value)} className="w-full pl-4 pr-8 py-2.5 bg-slate-50 border border-slate-100 rounded-xl text-xs font-bold text-slate-700 outline-none appearance-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-300 cursor-pointer">
                      <option value="ALL">所有设备分类</option>
                      {categories.map(cat => (
                          <option key={cat.id} value={cat.id}>{cat.name}</option>
                      ))}
                  </select>
                  <svg className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M19 9l-7 7-7-7" /></svg>
              </div>
          </div>
          <div className="flex items-center gap-2 overflow-x-auto no-scrollbar pb-1">
            <button onClick={() => setStatusFilter('ALL')} className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase transition-all border whitespace-nowrap ${statusFilter === 'ALL' ? 'bg-slate-800 border-slate-800 text-white shadow-md' : 'bg-white border-slate-100 text-slate-400 hover:bg-slate-50'}`}>All Status</button>
            {Object.values(DeviceStatus).map(s => (
                 <button key={s} onClick={() => setStatusFilter(s)} className={`px-4 py-2 rounded-xl text-[10px] font-black uppercase transition-all border whitespace-nowrap flex items-center gap-2 ${statusFilter === s ? 'bg-slate-800 border-slate-800 text-white shadow-md' : 'bg-white border-slate-100 text-slate-400 hover:bg-slate-50'}`}>
                     <div className={`w-1.5 h-1.5 rounded-full ${getStatusColor(s)}`}></div>
                     {s}
                 </button>
             ))}
          </div>
      </div>

      {/* --- Device Grid List --- */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-1">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {filteredDevices.map(device => {
                // Find Category Definition
                const category = categories.find(c => c.id === device.categoryId);
                
                // --- INTELLIGENT METRIC SELECTION LOGIC ---
                // 1. Get defined metrics from Category (schema source of truth)
                // Filter out 'ts' as it is not a display metric
                const definedMetrics = category?.metricDefinitions?.filter(m => m !== 'ts') || [];
                // 2. Get available runtime metrics
                const runtimeMetrics = Object.keys(device.metrics);
                
                // 3. Resolve Primary Key
                let primaryKey = category?.defaultDisplayMetric;
                
                // If default is not valid (not defined or no data), fall back to first defined metric
                if (!primaryKey || !runtimeMetrics.includes(primaryKey)) {
                    primaryKey = definedMetrics.find(k => runtimeMetrics.includes(k));
                }
                // If still no primary, fall back to any available runtime metric
                if (!primaryKey) {
                    primaryKey = runtimeMetrics[0];
                }
                
                // 4. Resolve Secondary Key (Next defined metric that isn't primary)
                let secondaryKey = definedMetrics.find(k => k !== primaryKey && runtimeMetrics.includes(k));
                // Fallback
                if (!secondaryKey) {
                    secondaryKey = runtimeMetrics.find(k => k !== primaryKey);
                }
                
                const primaryMetric = primaryKey ? device.metrics[primaryKey] : [];
                // PASS DEVICE TYPE FOR RESOLUTION
                const primaryConfig = resolveMetricMetadata(metricConfig, primaryKey, device.type);
                
                const secondaryMetric = secondaryKey ? device.metrics[secondaryKey] : [];
                // PASS DEVICE TYPE FOR RESOLUTION
                const secondaryConfig = resolveMetricMetadata(metricConfig, secondaryKey, device.type);

                return (
                    <div key={device.id} onClick={() => setSelectedDeviceId(device.id)} className="bg-white p-6 rounded-[32px] border border-slate-100 shadow-sm hover:shadow-xl hover:-translate-y-1 hover:border-indigo-200 transition-all cursor-pointer group relative overflow-hidden">
                        <div className={`absolute top-0 left-0 right-0 h-1.5 ${getStatusColor(device.status)} opacity-80`}></div>
                        <div className="flex justify-between items-start mb-5 mt-2">
                            <div>
                                <h4 className="font-bold text-slate-800 text-lg mb-1">{device.name}</h4>
                                <div className="flex items-center gap-2">
                                    <span className="text-[10px] bg-slate-100 text-slate-500 px-1.5 py-0.5 rounded font-bold uppercase">{device.type}</span>
                                    <span className="text-[10px] font-mono text-slate-400">{device.ip}</span>
                                </div>
                            </div>
                            <div className="w-8 h-8 rounded-full bg-slate-50 flex items-center justify-center text-slate-300 group-hover:bg-indigo-500 group-hover:text-white transition-colors">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
                            </div>
                        </div>
                        <div className="space-y-4">
                            {primaryKey ? (
                                <div>
                                    <div className="flex justify-between items-end mb-1">
                                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{primaryConfig.label}</span>
                                        <span className="text-xl font-black text-slate-700">
                                            {primaryMetric.length > 0 ? primaryMetric[primaryMetric.length-1].value : '-'} <span className="text-[10px] text-slate-400 font-bold">{primaryConfig.unit}</span>
                                        </span>
                                    </div>
                                    <div className="h-8 w-full opacity-60 group-hover:opacity-100 transition-opacity">
                                        <MiniSparkline data={primaryMetric.map(m => m.value)} color={primaryConfig.color} />
                                    </div>
                                </div>
                            ) : (
                                <div className="h-14 flex items-center justify-center text-[10px] text-slate-300 font-bold uppercase border-2 border-dashed border-slate-50 rounded-xl">No Metrics</div>
                            )}
                            {secondaryKey && (
                                <div className="flex justify-between items-center pt-3 border-t border-slate-50">
                                     <span className="text-[10px] font-bold text-slate-400 uppercase">{secondaryConfig.label}</span>
                                     <span className="text-xs font-black text-slate-600">
                                        {secondaryMetric.length > 0 ? secondaryMetric[secondaryMetric.length-1].value : '-'} {secondaryConfig.unit}
                                     </span>
                                </div>
                            )}
                        </div>
                    </div>
                );
            })}
            {filteredDevices.length === 0 && (
                 <div className="col-span-full text-center py-20 bg-white rounded-[32px] border border-slate-100 border-dashed">
                     <p className="text-sm font-bold text-slate-400">No devices found</p>
                     <p className="text-xs text-slate-300 mt-1">Try changing the status filter.</p>
                 </div>
            )}
        </div>
      </div>

      {/* --- Detail Modal --- */}
      {selectedDevice && (
          <div className="fixed inset-0 z-[60] flex items-center justify-center p-6 bg-slate-900/80 backdrop-blur-md animate-in fade-in duration-300">
             <div className="bg-white rounded-[40px] shadow-2xl border border-white/40 w-full max-w-5xl h-[90vh] overflow-hidden animate-in zoom-in-95 duration-300 flex flex-col relative">
                <div className="p-8 border-b border-slate-100 bg-slate-50/50 flex justify-between items-start flex-shrink-0">
                    <div>
                        <div className="flex items-center gap-3 mb-2">
                            <h3 className="text-2xl font-black text-slate-800">{selectedDevice.name}</h3>
                            <span className={`px-2 py-0.5 rounded-lg text-[10px] font-black uppercase tracking-wider text-white ${getStatusColor(selectedDevice.status)}`}>{selectedDevice.status}</span>
                        </div>
                        <div className="flex items-center gap-4 text-xs font-medium text-slate-500">
                            <span className="flex items-center gap-1"><svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg> {selectedDevice.location}</span>
                            <span className="flex items-center gap-1"><svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" /></svg> {selectedDevice.id}</span>
                            <span className="font-mono bg-slate-100 px-1.5 rounded text-slate-400">{selectedDevice.ip}</span>
                        </div>
                    </div>
                    <div className="flex items-center gap-3">
                         <button onClick={handleAnalyze} className="px-5 py-2.5 bg-indigo-600 text-white rounded-xl font-bold text-xs hover:bg-indigo-700 transition-all shadow-lg hover:shadow-indigo-200 flex items-center gap-2">
                            {isAnalyzing ? <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div> : <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>}
                            {isAnalyzing ? 'Analyzing...' : 'AI Diagnostic'}
                        </button>
                        {diagnosticReport && !isAnalyzing && (
                            <button onClick={handleExportPDF} className="px-5 py-2.5 bg-rose-50 text-rose-600 rounded-xl font-bold text-xs hover:bg-rose-100 transition-all border border-rose-100 flex items-center gap-2 animate-in fade-in zoom-in"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>Export PDF</button>
                        )}
                        <button onClick={handleCloseModal} className="p-2.5 text-slate-400 hover:text-rose-500 hover:bg-rose-50 rounded-xl transition-colors"><svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" /></svg></button>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto custom-scrollbar p-8 bg-slate-50/30">
                    {diagnosticReport && (
                        <div className="mb-8 p-6 bg-gradient-to-br from-indigo-50 to-white rounded-[24px] border border-indigo-100 animate-in fade-in slide-in-from-top-4 shadow-sm">
                             <div className="flex items-center gap-2 mb-3">
                                 <span className="text-xs font-black text-indigo-500 uppercase tracking-widest">Gemini Insight</span>
                                 <span className={`px-2 py-0.5 rounded text-[10px] font-black uppercase ${diagnosticReport.status === 'Healthy' ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600'}`}>{diagnosticReport.status}</span>
                             </div>
                             <p className="text-sm text-slate-700 leading-relaxed font-medium mb-4">{diagnosticReport.summary}</p>
                             <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                 <div className="bg-white p-4 rounded-xl border border-slate-100">
                                     <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Recommendations</h5>
                                     <ul className="list-disc list-inside text-xs text-slate-600 space-y-1">
                                         {diagnosticReport.recommendations.map((rec, i) => <li key={i}>{rec}</li>)}
                                     </ul>
                                 </div>
                                 <div className="bg-white p-4 rounded-xl border border-slate-100">
                                     <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Anomalies Detected</h5>
                                     <ul className="list-disc list-inside text-xs text-slate-600 space-y-1">
                                         {diagnosticReport.anomaliesFound.length > 0 ? diagnosticReport.anomaliesFound.map((rec, i) => <li key={i}>{rec}</li>) : <li>None detected</li>}
                                     </ul>
                                 </div>
                             </div>
                        </div>
                    )}

                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {Object.entries(selectedDevice.metrics).map(([key, history]) => {
                            // PASS DEVICE TYPE FOR RESOLUTION
                            const config = resolveMetricMetadata(metricConfig, key, selectedDevice.type);
                            const latestVal = history.length > 0 ? history[history.length - 1].value : 0;
                            const prevVal = history.length > 1 ? history[history.length - 2].value : latestVal;
                            const isRising = latestVal > prevVal;

                            return (
                                <div key={key} className="bg-white p-6 rounded-[24px] border border-slate-100 shadow-sm hover:border-indigo-100 transition-all group">
                                    <div className="flex justify-between items-start mb-4">
                                        <div>
                                            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{config.label}</p>
                                            <div className="flex items-baseline gap-1 mt-1">
                                                <span className="text-3xl font-black text-slate-800 tracking-tight">{latestVal}</span>
                                                <span className="text-xs font-bold text-slate-400">{config.unit}</span>
                                            </div>
                                        </div>
                                        <div className={`w-10 h-10 rounded-full flex items-center justify-center ${isRising ? 'bg-rose-50 text-rose-500' : 'bg-emerald-50 text-emerald-500'}`}>
                                            <svg className={`w-5 h-5 transform ${isRising ? '-rotate-45' : 'rotate-45'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg>
                                        </div>
                                    </div>
                                    <div className="h-16 w-full">
                                        <MiniSparkline data={history.map(d => d.value)} color={config.color} />
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
             </div>
          </div>
      )}
    </div>
  );
};
