
import React, { useState, useMemo } from 'react';
import { Device, DeviceStatus, DiagnosticReport, DeviceCategory, MetricConfig } from '../types';
import { getDeviceDiagnostic } from '../geminiService';
import { jsPDF } from "jspdf";
import { resolveMetricMetadata } from '../constants';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { Input, Select } from '../components/ui/Input';
import { Badge } from '../components/ui/Badge';
import { Modal } from '../components/ui/Modal';

interface MonitorPageProps {
  devices: Device[];
  categories: DeviceCategory[];
  metricConfig: MetricConfig;
}

const getStatusVariant = (status: DeviceStatus) => {
    switch (status) {
      case DeviceStatus.ONLINE: return 'success';
      case DeviceStatus.WARNING: return 'warning';
      case DeviceStatus.CRITICAL: return 'danger';
      default: return 'neutral';
    }
};

const MiniSparkline = ({ data, color }: { data: number[], color: string }) => {
  if (!data || data.length === 0) return <div className="w-full h-8 bg-slate-50 rounded-lg"></div>;
  
  const max = Math.max(...data) * 1.1 || 100;
  const min = 0;
  const range = max - min;
  
  const points = data.map((v, i) => {
      const x = (i / (data.length - 1)) * 100;
      const y = 100 - ((v - min) / range) * 100;
      return `${x},${y}`;
  }).join(' ');

  return (
    <svg className="w-full h-8 overflow-visible" viewBox="0 0 100 100" preserveAspectRatio="none">
      <polyline 
        fill="none" 
        stroke={color} 
        strokeWidth="4" 
        strokeLinecap="round" 
        strokeLinejoin="round" 
        points={points} 
        vectorEffect="non-scaling-stroke"
      />
    </svg>
  );
};

export const MonitorPage: React.FC<MonitorPageProps> = ({ devices, categories, metricConfig }) => {
  const [selectedDeviceId, setSelectedDeviceId] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [diagnosticReport, setDiagnosticReport] = useState<DiagnosticReport | null>(null);
  
  // Filter States
  const [statusFilter, setStatusFilter] = useState<DeviceStatus | 'ALL'>('ALL');
  const [categoryFilter, setCategoryFilter] = useState<string>('ALL');
  const [searchQuery, setSearchQuery] = useState('');

  const selectedDevice = useMemo(() => 
    selectedDeviceId ? devices.find(d => d.id === selectedDeviceId) : null, 
  [devices, selectedDeviceId]);

  const filteredDevices = useMemo(() => {
      return devices.filter(d => {
          const matchStatus = statusFilter === 'ALL' || d.status === statusFilter;
          const matchCategory = categoryFilter === 'ALL' || d.categoryId === categoryFilter;
          const matchSearch = !searchQuery || 
              d.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
              d.ip.includes(searchQuery) ||
              d.id.toLowerCase().includes(searchQuery.toLowerCase());
          
          return matchStatus && matchCategory && matchSearch;
      });
  }, [devices, statusFilter, categoryFilter, searchQuery]);

  const handleAnalyze = async () => {
    if (!selectedDevice) return;
    setIsAnalyzing(true);
    setDiagnosticReport(null);
    const report = await getDeviceDiagnostic(selectedDevice);
    setDiagnosticReport(report);
    setIsAnalyzing(false);
  };

  const handleExportPDF = () => {
      if (!selectedDevice || !diagnosticReport) return;
      const doc = new jsPDF();
      doc.setFontSize(20);
      doc.text("AI Diagnostic Report", 20, 20);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(`Generated by AuraSense AI • ${new Date().toLocaleString()}`, 20, 26);
      doc.setDrawColor(200);
      doc.line(20, 30, 190, 30);
      doc.setTextColor(0);
      doc.setFontSize(12);
      doc.text(`Device Name: ${selectedDevice.name}`, 20, 40);
      doc.text(`Device ID: ${selectedDevice.id}`, 20, 46);
      doc.text(`Type: ${selectedDevice.type}`, 120, 40);
      doc.text(`Location: ${selectedDevice.location}`, 120, 46);
      doc.setFontSize(14);
      doc.text("Health Assessment", 20, 60);
      doc.setFontSize(12);
      if (diagnosticReport.status === 'Healthy') doc.setTextColor(0, 150, 0);
      else if (diagnosticReport.status === 'Risk') doc.setTextColor(200, 100, 0);
      else doc.setTextColor(200, 0, 0);
      doc.text(`Status: ${diagnosticReport.status.toUpperCase()}`, 20, 68);
      doc.setTextColor(0);
      doc.setFontSize(14);
      doc.text("Executive Summary", 20, 85);
      doc.setFontSize(10);
      doc.setTextColor(60);
      const summaryLines = doc.splitTextToSize(diagnosticReport.summary, 170);
      doc.text(summaryLines, 20, 93);
      let currentY = 93 + summaryLines.length * 5 + 10;
      doc.setTextColor(0);
      doc.setFontSize(14);
      doc.text("Detected Anomalies", 20, currentY);
      currentY += 8;
      doc.setFontSize(10);
      doc.setTextColor(60);
      if (diagnosticReport.anomaliesFound.length > 0) {
          diagnosticReport.anomaliesFound.forEach(anomaly => {
              doc.text(`• ${anomaly}`, 20, currentY);
              currentY += 6;
          });
      } else {
          doc.text("• No anomalies detected.", 20, currentY);
          currentY += 6;
      }
      currentY += 10;
      doc.setTextColor(0);
      doc.setFontSize(14);
      doc.text("Actionable Recommendations", 20, currentY);
      currentY += 8;
      doc.setFontSize(10);
      doc.setTextColor(60);
      diagnosticReport.recommendations.forEach(rec => {
          doc.text(`• ${rec}`, 20, currentY);
          currentY += 6;
      });
      doc.save(`AuraSense_Report_${selectedDevice.id}_${Date.now()}.pdf`);
  };

  const handleCloseModal = () => {
      setSelectedDeviceId(null);
      setDiagnosticReport(null);
      setIsAnalyzing(false);
  };

  return (
    <div className="flex flex-col h-full space-y-6">
      {/* Filter Bar */}
      <Card className="flex flex-col xl:flex-row justify-between xl:items-center gap-4 p-4 flex-shrink-0">
          <div className="flex flex-col md:flex-row md:items-center gap-4 flex-1">
              <div>
                  <h3 className="text-lg font-black text-slate-800">全域设备监控</h3>
                  <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Global Device Monitoring</p>
              </div>
              <div className="hidden md:block w-px h-8 bg-slate-100"></div>
              <div className="flex-1 max-w-sm">
                  <Input 
                    value={searchQuery} 
                    onChange={(e) => setSearchQuery(e.target.value)} 
                    placeholder="搜索设备名称 / IP / ID..." 
                    icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>}
                    className="py-2.5 text-xs"
                  />
              </div>
              <div className="w-48">
                  <Select 
                    value={categoryFilter} 
                    onChange={(e) => setCategoryFilter(e.target.value)}
                    className="py-2.5 text-xs"
                    options={[
                        { label: '所有设备分类', value: 'ALL' },
                        ...categories.map(cat => ({ label: cat.name, value: cat.id }))
                    ]}
                  />
              </div>
          </div>
          <div className="flex items-center gap-2 overflow-x-auto no-scrollbar pb-1">
            <Button 
                variant={statusFilter === 'ALL' ? 'primary' : 'secondary'}
                size="sm"
                onClick={() => setStatusFilter('ALL')}
                className={statusFilter === 'ALL' ? 'bg-slate-800 text-white border-slate-800 shadow-md' : ''}
            >
                All Status
            </Button>
            {Object.values(DeviceStatus).map(s => (
                 <Button 
                    key={s} 
                    variant={statusFilter === s ? 'primary' : 'secondary'}
                    size="sm"
                    onClick={() => setStatusFilter(s)} 
                    className={statusFilter === s ? 'bg-slate-800 text-white border-slate-800 shadow-md' : ''}
                 >
                     <div className={`w-1.5 h-1.5 rounded-full mr-2 ${s === DeviceStatus.ONLINE ? 'bg-emerald-400' : s === DeviceStatus.WARNING ? 'bg-amber-400' : 'bg-rose-400'}`}></div>
                     {s}
                 </Button>
             ))}
          </div>
      </Card>

      {/* --- Device Grid List --- */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-1">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {filteredDevices.map(device => {
                const category = categories.find(c => c.id === device.categoryId);
                const definedMetrics = category?.metricDefinitions?.filter(m => m !== 'ts') || [];
                const runtimeMetrics = Object.keys(device.metrics);
                
                let primaryKey = category?.defaultDisplayMetric;
                if (!primaryKey || !runtimeMetrics.includes(primaryKey)) {
                    primaryKey = definedMetrics.find(k => runtimeMetrics.includes(k));
                }
                if (!primaryKey) primaryKey = runtimeMetrics[0];
                
                let secondaryKey = definedMetrics.find(k => k !== primaryKey && runtimeMetrics.includes(k));
                if (!secondaryKey) secondaryKey = runtimeMetrics.find(k => k !== primaryKey);
                
                const primaryMetric = primaryKey ? device.metrics[primaryKey] : [];
                const primaryConfig = resolveMetricMetadata(metricConfig, primaryKey, device.type);
                
                const secondaryMetric = secondaryKey ? device.metrics[secondaryKey] : [];
                const secondaryConfig = resolveMetricMetadata(metricConfig, secondaryKey, device.type);

                return (
                    <Card key={device.id} hoverEffect onClick={() => setSelectedDeviceId(device.id)} className="relative overflow-hidden group">
                        <div className={`absolute top-0 left-0 right-0 h-1.5 opacity-80 ${device.status === DeviceStatus.ONLINE ? 'bg-emerald-500' : device.status === DeviceStatus.WARNING ? 'bg-amber-500' : device.status === DeviceStatus.CRITICAL ? 'bg-rose-500' : 'bg-slate-400'}`}></div>
                        <div className="flex justify-between items-start mb-5 mt-2">
                            <div>
                                <h4 className="font-bold text-slate-800 text-lg mb-1">{device.name}</h4>
                                <div className="flex items-center gap-2">
                                    <Badge variant="neutral">{device.type}</Badge>
                                    <span className="text-[10px] font-mono text-slate-400">{device.ip}</span>
                                </div>
                            </div>
                            <div className="w-8 h-8 rounded-full bg-slate-50 flex items-center justify-center text-slate-300 group-hover:bg-indigo-500 group-hover:text-white transition-colors">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7l5 5m0 0l-5 5m5-5H6" /></svg>
                            </div>
                        </div>
                        <div className="space-y-4">
                            {primaryKey ? (
                                <div>
                                    <div className="flex justify-between items-end mb-1">
                                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{primaryConfig.label}</span>
                                        <span className="text-xl font-black text-slate-700">
                                            {primaryMetric.length > 0 ? primaryMetric[primaryMetric.length-1].value : '-'} <span className="text-[10px] text-slate-400 font-bold">{primaryConfig.unit}</span>
                                        </span>
                                    </div>
                                    <div className="h-8 w-full opacity-60 group-hover:opacity-100 transition-opacity">
                                        <MiniSparkline data={primaryMetric.map(m => m.value)} color={primaryConfig.color} />
                                    </div>
                                </div>
                            ) : (
                                <div className="h-14 flex items-center justify-center text-[10px] text-slate-300 font-bold uppercase border-2 border-dashed border-slate-50 rounded-xl">No Metrics</div>
                            )}
                            {secondaryKey && (
                                <div className="flex justify-between items-center pt-3 border-t border-slate-50">
                                     <span className="text-[10px] font-bold text-slate-400 uppercase">{secondaryConfig.label}</span>
                                     <span className="text-xs font-black text-slate-600">
                                        {secondaryMetric.length > 0 ? secondaryMetric[secondaryMetric.length-1].value : '-'} {secondaryConfig.unit}
                                     </span>
                                </div>
                            )}
                        </div>
                    </Card>
                );
            })}
            {filteredDevices.length === 0 && (
                 <div className="col-span-full text-center py-20 bg-white rounded-[32px] border border-slate-100 border-dashed">
                     <p className="text-sm font-bold text-slate-400">No devices found</p>
                     <p className="text-xs text-slate-300 mt-1">Try changing the status filter.</p>
                 </div>
            )}
        </div>
      </div>

      {/* --- Detail Modal --- */}
      <Modal
        isOpen={!!selectedDevice}
        onClose={handleCloseModal}
        title={selectedDevice?.name || ''}
        subtitle="Device Diagnostic & Details"
        size="xl"
        footer={
            <div className="flex justify-end gap-3 w-full">
                {diagnosticReport && !isAnalyzing && (
                    <Button variant="secondary" onClick={handleExportPDF} icon={<svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>}>
                        Export PDF
                    </Button>
                )}
                <Button 
                    variant="primary" 
                    onClick={handleAnalyze} 
                    disabled={isAnalyzing}
                    icon={isAnalyzing ? <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin"></div> : <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>}
                >
                    {isAnalyzing ? 'Analyzing...' : 'AI Diagnostic'}
                </Button>
            </div>
        }
      >
        {selectedDevice && (
            <div className="space-y-6">
                {/* Meta Info */}
                <div className="flex items-center gap-4 text-xs font-medium text-slate-500 bg-slate-50 p-4 rounded-2xl border border-slate-100">
                    <span className="flex items-center gap-1"><Badge variant={getStatusVariant(selectedDevice.status)} dot>{selectedDevice.status}</Badge></span>
                    <span className="flex items-center gap-1"><svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg> {selectedDevice.location}</span>
                    <span className="flex items-center gap-1"><svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" /></svg> {selectedDevice.id}</span>
                    <span className="font-mono bg-white px-2 py-0.5 rounded border border-slate-200 text-slate-600">{selectedDevice.ip}</span>
                </div>

                {/* AI Report */}
                {diagnosticReport && (
                    <div className="p-6 bg-gradient-to-br from-indigo-50 to-white rounded-[24px] border border-indigo-100 animate-in fade-in slide-in-from-top-4 shadow-sm">
                            <div className="flex items-center gap-2 mb-3">
                                <span className="text-xs font-black text-indigo-500 uppercase tracking-widest">Gemini Insight</span>
                                <Badge variant={diagnosticReport.status === 'Healthy' ? 'success' : 'danger'} dot>{diagnosticReport.status}</Badge>
                            </div>
                            <p className="text-sm text-slate-700 leading-relaxed font-medium mb-4">{diagnosticReport.summary}</p>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="bg-white p-4 rounded-xl border border-slate-100">
                                    <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Recommendations</h5>
                                    <ul className="list-disc list-inside text-xs text-slate-600 space-y-1">
                                        {diagnosticReport.recommendations.map((rec, i) => <li key={i}>{rec}</li>)}
                                    </ul>
                                </div>
                                <div className="bg-white p-4 rounded-xl border border-slate-100">
                                    <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Anomalies Detected</h5>
                                    <ul className="list-disc list-inside text-xs text-slate-600 space-y-1">
                                        {diagnosticReport.anomaliesFound.length > 0 ? diagnosticReport.anomaliesFound.map((rec, i) => <li key={i}>{rec}</li>) : <li>None detected</li>}
                                    </ul>
                                </div>
                            </div>
                    </div>
                )}

                {/* Charts Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {Object.entries(selectedDevice.metrics).map(([key, history]) => {
                        const config = resolveMetricMetadata(metricConfig, key, selectedDevice.type);
                        const latestVal = history.length > 0 ? history[history.length - 1].value : 0;
                        const prevVal = history.length > 1 ? history[history.length - 2].value : latestVal;
                        const isRising = latestVal > prevVal;

                        return (
                            <div key={key} className="bg-white p-6 rounded-[24px] border border-slate-100 shadow-sm hover:border-indigo-100 transition-all group">
                                <div className="flex justify-between items-start mb-4">
                                    <div>
                                        <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{config.label}</p>
                                        <div className="flex items-baseline gap-1 mt-1">
                                            <span className="text-3xl font-black text-slate-800 tracking-tight">{latestVal}</span>
                                            <span className="text-xs font-bold text-slate-400">{config.unit}</span>
                                        </div>
                                    </div>
                                    <div className={`w-10 h-10 rounded-full flex items-center justify-center ${isRising ? 'bg-rose-50 text-rose-500' : 'bg-emerald-50 text-emerald-500'}`}>
                                        <svg className={`w-5 h-5 transform ${isRising ? '-rotate-45' : 'rotate-45'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M14 5l7 7m0 0l-7 7m7-7H3"/></svg>
                                    </div>
                                </div>
                                <div className="h-16 w-full">
                                    <MiniSparkline data={history.map(d => d.value)} color={config.color} />
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        )}
      </Modal>
    </div>
  );
};
